name: Bug report
description: Report a reproducible problem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please do not attach Revit project files, proprietary data, or Autodesk materials.
  - type: checkboxes
    attributes:
      label: Pre-check
      options:
        - label: I searched existing issues and discussions.
          required: true
        - label: I can reproduce the issue with the latest version in this repo.
          required: true
  - type: textarea
    attributes:
      label: Summary
      description: A clear and concise description of the problem.
      placeholder: What went wrong?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Include commands, UI steps, or minimal code.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      placeholder: What actually happened?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs or screenshots
      description: Paste logs here. No proprietary or licensed files.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: Revit version, OS, add-in/server versions, etc.
      placeholder: |
        Revit:
        OS:
        Add-in/Server:
    validations:
      required: true
