name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
        Please avoid sharing proprietary data or Autodesk materials.
  - type: checkboxes
    attributes:
      label: Pre-check
      options:
        - label: I searched existing issues and discussions.
          required: true
  - type: textarea
    attributes:
      label: Problem / Need
      description: What problem are you trying to solve?
      placeholder: Describe the user need or pain point.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or workarounds?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Screenshots, mockups, or other relevant details.
    validations:
      required: false
