using System;
using System.Collections.Generic;

namespace IfcCore;

public interface IIfcLoader
{
    IfcModel Load(string path);
}

public interface IAnalyzer
{
    AnalysisResult Analyze(IEnumerable<string> files);
}

public interface IProfileGen
{
    ProfileDefinition Generate(AnalysisResult result, double minFillRate);
}

public interface IProfileCheck
{
    CheckResult Check(IfcModel model, ProfileDefinition profile, string targetFile);
}

public class Analyzer : IAnalyzer
{
    private readonly IIfcLoader _loader;

    public Analyzer(IIfcLoader loader) => _loader = loader ?? throw new ArgumentNullException(nameof(loader));

    public AnalysisResult Analyze(IEnumerable<string> files)
    {
        var r = new AnalysisResult();

        foreach (var f in files)
        {
            if (string.IsNullOrWhiteSpace(f)) continue;

            var model = _loader.Load(f);
            r.SourceFiles.Add(model.SourcePath);

            foreach (var kv in model.EntitiesByType)
            {
                var type = kv.Key;
                var list = kv.Value;

                var es = r.GetOrAdd(type);
                es.InstanceCount += list.Count;

                foreach (var ent in list)
                {
                    foreach (var p in ent.Properties)
                    {
                        var ps = es.GetOrAdd(p.Key);
                        ps.Register(ent.Id, p.Value);
                    }
                }
            }
        }

        return r;
    }
}

public class ProfileGen : IProfileGen
{
    public ProfileDefinition Generate(AnalysisResult result, double minFillRate)
    {
        if (result == null) throw new ArgumentNullException(nameof(result));
        if (minFillRate < 0 || minFillRate > 1) throw new ArgumentOutOfRangeException(nameof(minFillRate));

        var p = new ProfileDefinition
        {
            ProfileName = "AutoGeneratedProfile",
            ProfileVersion = "1.0.0",
            CreatedAt = DateTime.UtcNow,
            SourceFiles = new List<string>(result.SourceFiles)
        };

        foreach (var ek in result.Entities)
        {
            var type = ek.Key;
            var es = ek.Value;
            var rule = new EntityRule();

            foreach (var pk in es.Properties)
            {
                var key = pk.Key;
                var ps = pk.Value;
                if (ps.EntityCount == 0) continue;

                var rate = ps.FillRate;
                if (rate >= minFillRate)
                {
                    rule.RequiredProperties.Add(new RequiredPropertyRule
                    {
                        Pset = key.Pset,
                        Name = key.Prop,
                        MinFillRate = rate
                    });
                }
            }

            if (rule.RequiredProperties.Count > 0)
            {
                p.EntityRules[type] = rule;
            }
        }

        return p;
    }
}

public class ProfileCheck : IProfileCheck
{
    public CheckResult Check(IfcModel model, ProfileDefinition profile, string targetFile)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));
        if (profile == null) throw new ArgumentNullException(nameof(profile));

        var r = new CheckResult
        {
            Ok = true,
            ProfileName = profile.ProfileName,
            TargetFile = string.IsNullOrWhiteSpace(targetFile) ? model.SourcePath : targetFile
        };

        foreach (var ek in profile.EntityRules)
        {
            var type = ek.Key;
            var rule = ek.Value;

            if (!model.EntitiesByType.TryGetValue(type, out var list) || list.Count == 0)
            {
                foreach (var req in rule.RequiredProperties)
                {
                    r.Items.Add(new CheckItem
                    {
                        Severity = "error",
                        EntityName = type,
                        Pset = req.Pset,
                        Property = req.Name,
                        Message = $"No instances of {type} found while profile requires {req.Pset}.{req.Name}."
                    });
                    r.Summary.ErrorCount++;
                }
                r.Ok = false;
                continue;
            }

            foreach (var ent in list)
            {
                foreach (var req in rule.RequiredProperties)
                {
                    var key = new PropertyKey(req.Pset, req.Name);
                    if (!ent.Properties.TryGetValue(key, out var hasValue) || !hasValue)
                    {
                        r.Items.Add(new CheckItem
                        {
                            Severity = "error",
                            EntityName = type,
                            IfcGuid = string.IsNullOrWhiteSpace(ent.GlobalId) ? $"#{ent.Id}" : ent.GlobalId,
                            Pset = req.Pset,
                            Property = req.Name,
                            Message = "Missing required property or value."
                        });
                        r.Summary.ErrorCount++;
                        r.Ok = false;
                    }
                }
            }
        }

        return r;
    }
}

